## 2

In [2]:
import torch

In [11]:
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000):
    s += torch.tensor(0.01,dtype=torch.float32)
print(s)

tensor(10.0001)

In [12]:
s = torch.tensor(0,dtype=torch.float16)
for i in range(1000):
    s += torch.tensor(0.01,dtype=torch.float16)
print(s)

tensor(9.9531, dtype=torch.float16)

In [13]:
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000):
    s += torch.tensor(0.01,dtype=torch.float16)
print(s)

tensor(10.0021)

In [14]:
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000):
    x = torch.tensor(0.01,dtype=torch.float16)
    s += x.type(torch.float32)
print(s)

tensor(10.0021)

## 4

In [1]:
import pandas as pd
import numpy as np

In [2]:
compiled = pd.read_csv("./results/attn_bench/attn_compiled.csv")
uncompiled = pd.read_csv("./results/attn_bench/attn_uncompiled.csv")

In [9]:
print(compiled.to_latex(index=False,float_format="%.2f", caption="attention benchmarking with torch.compile",label="table:with_torch_compile_attention"))

\begin{table}
\caption{attention benchmarking with torch.compile}
\label{table:with_torch_compile_attention}
\begin{tabular}{rrrrrrl}
\toprule
d & T & fwd_ms & mem_before_bwd_mib & bwd_ms & peak_mib & status \\
\midrule
16 & 256 & 9.50 & 20.91 & 0.63 & 25.03 & success \\
16 & 1024 & 15.84 & 82.88 & 0.66 & 208.75 & success \\
16 & 4096 & 0.81 & 1050.75 & 1.94 & 2076.75 & success \\
16 & 8192 & 3.12 & 4133.25 & 6.48 & 8233.25 & success \\
16 & 16384 & 23.58 & 16442.25 & 23.79 & 32834.25 & success \\
32 & 256 & 14.04 & 21.53 & 0.54 & 25.78 & success \\
32 & 1024 & 0.15 & 85.38 & 0.55 & 150.38 & success \\
32 & 4096 & 1.09 & 1060.75 & 2.19 & 2088.75 & success \\
32 & 8192 & 4.01 & 4153.25 & 8.08 & 8257.25 & success \\
32 & 16384 & 28.27 & 16481.75 & 58.77 & 49265.75 & success \\
64 & 256 & 0.13 & 22.78 & 0.60 & 27.28 & success \\
64 & 1024 & 0.17 & 90.38 & 0.56 & 156.38 & success \\
64 & 4096 & 1.40 & 1080.75 & 2.83 & 2112.75 & success \\
64 & 8192 & 5.23 & 4193.25 & 10.03 & 8305.25 & success \\
64 & 16384 & 33.31 & 16561.75 & 68.71 & 49361.75 & success \\
128 & 256 & 0.13 & 25.28 & 0.58 & 30.28 & success \\
128 & 1024 & 0.21 & 100.38 & 0.60 & 168.38 & success \\
128 & 4096 & 1.96 & 1120.75 & 3.95 & 2160.75 & success \\
128 & 8192 & 7.53 & 4273.25 & 14.87 & 8401.25 & success \\
128 & 16384 & 41.89 & 16721.75 & 85.30 & 49553.75 & success \\
\bottomrule
\end{tabular}
\end{table}

In [10]:
print(uncompiled.to_latex(index=False,float_format="%.2f", caption="attention benchmarking without torch.compile",label="table:no_torch_compile_attention"))

\begin{table}
\caption{attention benchmarking without torch.compile}
\label{table:no_torch_compile_attention}
\begin{tabular}{rrrrrrl}
\toprule
d & T & fwd_ms & mem_before_bwd_mib & bwd_ms & peak_mib & status \\
\midrule
16 & 256 & 0.10 & 20.90 & 0.69 & 29.02 & success \\
16 & 1024 & 0.16 & 82.84 & 0.65 & 211.34 & success \\
16 & 4096 & 1.74 & 1050.63 & 4.03 & 3100.63 & success \\
16 & 8192 & 7.03 & 4133.00 & 15.06 & 12329.00 & success \\
16 & 16384 & 26.68 & 16441.75 & 57.20 & 49217.75 & success \\
32 & 256 & 0.10 & 21.52 & 0.68 & 29.77 & success \\
32 & 1024 & 0.16 & 85.34 & 0.69 & 214.34 & success \\
32 & 4096 & 1.82 & 1060.63 & 4.12 & 3112.63 & success \\
32 & 8192 & 7.37 & 4153.00 & 15.36 & 12353.00 & success \\
32 & 16384 & 28.18 & 16481.75 & 58.70 & 49265.75 & success \\
64 & 256 & 0.10 & 22.77 & 0.72 & 31.27 & success \\
64 & 1024 & 0.18 & 90.34 & 0.69 & 220.34 & success \\
64 & 4096 & 2.14 & 1080.63 & 4.73 & 3136.63 & success \\
64 & 8192 & 8.59 & 4193.00 & 17.56 & 12401.00 & success \\
64 & 16384 & 33.19 & 16561.75 & 68.61 & 49361.75 & success \\
128 & 256 & 0.10 & 25.27 & 0.73 & 34.27 & success \\
128 & 1024 & 0.22 & 100.34 & 0.75 & 232.34 & success \\
128 & 4096 & 2.69 & 1120.63 & 5.84 & 3184.63 & success \\
128 & 8192 & 10.88 & 4273.00 & 22.40 & 12497.00 & success \\
128 & 16384 & 41.78 & 16721.75 & 85.19 & 49553.75 & success \\
\bottomrule
\end{tabular}
\end{table}

In [55]:
compiled = pd.read_csv("./results/attn_bench/attn_compiled.csv")
uncompiled = pd.read_csv("./results/attn_bench/attn_uncompiled.csv")

In [56]:
compare = pd.merge(left=uncompiled,right=compiled[["d","T","fwd_ms","mem_before_bwd_mib","bwd_ms","peak_mib","status"]],on=["d","T"], how = "left",suffixes=("_uncom", "_comp"))

In [57]:
compare.head(5)

,d,T,fwd_ms_uncom,mem_before_bwd_mib_uncom,bwd_ms_uncom,peak_mib_uncom,status_uncom,fwd_ms_comp,mem_before_bwd_mib_comp,bwd_ms_comp,peak_mib_comp,status_comp
0,16,256,0.102815,20.898926,0.692417,29.024414,success,9.496885,20.906738,0.634103,25.032227,success
1,16,1024,0.157745,82.844238,0.646328,211.344727,success,15.844255,82.875488,0.660323,208.750000,success
2,16,4096,1.736502,1050.625488,4.032013,3100.625977,success,0.814003,1050.750488,1.941069,2076.750977,success
3,16,8192,7.034951,4133.000488,15.055877,12329.000977,success,3.115585,4133.250488,6.476749,8233.250977,success
4,16,16384,26.677864,16441.750488,57.204342,49217.750977,success,23.575268,16442.250488,23.787311,32834.250977,success

In [62]:
result = compare[["d","T", "fwd_ms_uncom","fwd_ms_comp","bwd_ms_uncom","bwd_ms_comp"]]

In [64]:
result["speedup_bwd"] = (result["bwd_ms_uncom"]/result["bwd_ms_comp"])

In [65]:
result.head(5)

,d,T,fwd_ms_uncom,fwd_ms_comp,bwd_ms_uncom,bwd_ms_comp,speedup_bwd
0,16,256,0.102815,9.496885,0.692417,0.634103,1.091962
1,16,1024,0.157745,15.844255,0.646328,0.660323,0.978806
2,16,4096,1.736502,0.814003,4.032013,1.941069,2.077212
3,16,8192,7.034951,3.115585,15.055877,6.476749,2.324604
4,16,16384,26.677864,23.575268,57.204342,23.787311,2.404826

In [38]:
print(result.to_latex(index=False,float_format="%.2f", caption="orch.compile vs. uncompiled attention",label="table:compare_attn"))

\begin{table}
\caption{orch.compile vs. uncompiled attention}
\label{table:compare_attn}
\begin{tabular}{rrrrrrr}
\toprule
d & T & fwd_ms_uncom & fwd_ms_comp & bwd_ms_uncom & bwd_ms_comp & speedup_bwd \\
\midrule
16 & 256 & 0.10 & 9.50 & 0.69 & 0.63 & 1.09 \\
16 & 1024 & 0.16 & 15.84 & 0.65 & 0.66 & 0.98 \\
16 & 4096 & 1.74 & 0.81 & 4.03 & 1.94 & 2.08 \\
16 & 8192 & 7.03 & 3.12 & 15.06 & 6.48 & 2.32 \\
16 & 16384 & 26.68 & 23.58 & 57.20 & 23.79 & 2.40 \\
32 & 256 & 0.10 & 14.04 & 0.68 & 0.54 & 1.26 \\
32 & 1024 & 0.16 & 0.15 & 0.69 & 0.55 & 1.27 \\
32 & 4096 & 1.82 & 1.09 & 4.12 & 2.19 & 1.88 \\
32 & 8192 & 7.37 & 4.01 & 15.36 & 8.08 & 1.90 \\
32 & 16384 & 28.18 & 28.27 & 58.70 & 58.77 & 1.00 \\
64 & 256 & 0.10 & 0.13 & 0.72 & 0.60 & 1.20 \\
64 & 1024 & 0.18 & 0.17 & 0.69 & 0.56 & 1.23 \\
64 & 4096 & 2.14 & 1.40 & 4.73 & 2.83 & 1.67 \\
64 & 8192 & 8.59 & 5.23 & 17.56 & 10.03 & 1.75 \\
64 & 16384 & 33.19 & 33.31 & 68.61 & 68.71 & 1.00 \\
128 & 256 & 0.10 & 0.13 & 0.73 & 0.58 & 1.26 \\
128 & 1024 & 0.22 & 0.21 & 0.75 & 0.60 & 1.25 \\
128 & 4096 & 2.69 & 1.96 & 5.84 & 3.95 & 1.48 \\
128 & 8192 & 10.88 & 7.53 & 22.40 & 14.87 & 1.51 \\
128 & 16384 & 41.78 & 41.89 & 85.19 & 85.30 & 1.00 \\
\bottomrule
\end{tabular}
\end{table}